### ISSUE TITLE
`make scf` with backend eks and custom kubeconfig fails upon `make clean`

### ISSUE THREAD

**Issue by greygoo** [SUSE/catapult#130]
When running 

```DEBUG_MODE=true HELM_VERSION=v3.1.1 SCF_OPERATOR=true CLUSTER_NAME=eks_test-2 BACKEND=eks KUBECFG=/data/src/suse/catapult/buildeks_test/kubeconfig make scf```

to deploy scf with a custom helm version and kubeconfig on an existing eks cluster, it fails with

```
+ . .envrc
./clean.sh: line 5: .envrc: No such file or directory
make[1]: *** [Makefile:5: clean] Error 1
make[1]: Leaving directory '/data/src/suse/catapult/modules/scf'
make: *** [Makefile:181: scf] Error 2
```

this is due to the fact that the new builddir which is derived from the clustername does not yet exist when the ```make clean``` step attempts to clean it up.

**Comment by viccuad** [comment]
`CLUSTER_NAME=foo <vars> make k8s` or `CLUSTER_NAME=foo <vars> make kubeconfig` will create a `buildfoo` folder.

Once you have that, you can deploy scf targetting that cluster on that folder: `CLUSTER_NAME=foo <vars> make scf`.

From rocketchat, one needs to be sure one is using the correct name on `CLUSTER_NAME`, or `make scf` will have no folder to operate on.

Closing, then.
