### ISSUE TITLE
caasp4 is still not working

### ISSUE THREAD

**Issue by prabalsharma** [SUSE/catapult#134]
I don't know if the previous fix (https://github.com/SUSE/catapult/pull/119, https://github.com/SUSE/catapult/issues/121)  was tested by deleting sukba image along with sle15 image.

it gets stuck on
```
Step 9/18 : RUN zypper refresh; zypper -n dist-upgrade
 ---> Running in 5f13a2de757d
Retrieving repository 'CAASP_pool' metadata [...............
```
this was on `opensuse` ^

deploying on `mac` gives me more info
```
Step 9/18 : RUN zypper refresh; zypper -n dist-upgrade
 ---> Running in 400039362e5b
Retrieving repository 'CAASP_pool' metadata [.error]
Repository 'CAASP_pool' is invalid.
[CAASP_pool|http://download.suse.de/ibs/SUSE/Products/SUSE-CAASP/4.0/x86_64/product] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'CAASP_pool' because of the above error.
Retrieving repository 'SLE-Module-Basesystem_pool' metadata [.error]
Repository 'SLE-Module-Basesystem_pool' is invalid.
[SLE-Module-Basesystem_pool|http://download.suse.de/ibs/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'SLE-Module-Basesystem_pool' because of the above error.
```
I am not sure if I am making some mistake. All I did was
`eval $(ssh-agent); source ../../workbench/ecp/cap-qa-openrc.sh; BACKEND=caasp4os CLUSTER_NAME=prabal-catapult make k8s;`

I am on commit 
```
commit 3b7fc2eb17118c8fc7d4d60ed86599c0e9b54e1d (HEAD -> refs/heads/master, refs/remotes/origin/master, refs/remotes/origin/HEAD)
Merge: 00f82b8 d50f280
Author: Victor Cuadrado Juan <viccuad@users.noreply.github.com>
Date:   Fri Mar 13 16:19:02 2020 +0100

    Merge pull request #132 from SUSE/fix-gke-helm
    
    Consume fixes for initializing helm, on gke```

**Comment by viccuad** [comment]
Stalling when retrieving repository metadata from download.suse.de sounds like the VPN from nuremberg offices being overloaded (particularly these last 2 days, when all employees are working from home).

Maybe we should add a switch to change the mirrors to use.
In the past I parametrized them: https://github.com/SUSE/catapult/blob/master/backend/caasp4os/docker/skuba/Dockerfile#L7

Do you know of any NA mirrors that can be used?

**Comment by prabalsharma** [comment]
> Stalling when retrieving repository metadata from download.suse.de sounds like the VPN from nuremberg offices being overloaded (particularly these last 2 days, when all employees are working from home).
> 
> Maybe we should add a switch to change the mirrors to use.
> In the past I parametrized them: https://github.com/SUSE/catapult/blob/master/backend/caasp4os/docker/skuba/Dockerfile#L7
> 
> Do you know of any NA mirrors that can be used?

no idea. @mook-as @HartS any idea?

**Comment by mook-as** [comment]
There's a mirror somewhere in Provo, I believe.
