### ISSUE TITLE
catapult should create ClusterReference file instead of gke kubeconfigs with expiry 

### ISSUE THREAD

**Issue by prabalsharma** [SUSE/catapult#175]
catapult needs to manage GKE state via ClusterReference file containing info which (in combination with user's GKE credentials) can be used to grab the kubeconfig from gcloud cli

```
--- 
kind: ClusterReference 
platform: gke 
cluster-name: concourse-gke-4a8f6df9d0fbb62b 
cluster-zone: us-west1-a
```

Right now catapult is using kubeconfig with expiry. With this implementation, catapult will use ClusterReference file (which will go to pools), to generate kubeconfigs on the fly to interact with `kubectl`

**Comment by prabalsharma** [comment]
@viccuad do you have any thoughts on how this will be implemented? In old CI, we were generating kubeconfigs from  ClusterReference file (pulling from pools), during start of each container (concourse task). 
To handle this in Catapult, should we generate kubeconfig for each make target or should be keep Catapult as it is and just add additional ClusterReference file to `build folder` along with existing kubeconfig with expiry (for local usage), for CI usage.

**Comment by prabalsharma** [comment]
I think instead of changing mechanism of catapult for local deployment (as it work well), we must just add ClusterReference file in `gke build folder` for CI consumption. But then we will have to generate kubeconfig for each concourse task (which is not a bad thing).

**Comment by HartS** [comment]
Yes, but I don't think catapult should just provide this file for consumption by CI (CI is just giving it back to catapult after all), it needs to provide the functionality which runs `gke auth` based on that information (as well as credentials). When catapult is used to provision, modify, inspect, or destroy GKE backends it should take the ClusterReference file if provided and generate a single-use kubeconfig which it then uses for its operations

**Comment by andreas-kupries** [comment]
@prabalsharma @HartS Noting the `In old CI, we were generating kubeconfigs from ClusterReference file (pulling from pools), ...` in https://github.com/SUSE/catapult/issues/175#issuecomment-614340356 I believe it would be useful to get a reference to this code, and related things.

**Comment by viccuad** [comment]
GKE kubeconfigs provided by catapult are just the output of https://github.com/SUSE/cap-terraform.
It [calls `terraform apply`](https://github.com/SUSE/catapult/blob/master/backend/gke/deploy.sh#L48), and since the `KUBECONFIG` env var is set up for inside the buildfolder, it gets saved there.

If the kubeconfig is with expiry, we need to fix it, yes. Either in catapult or cap-terraform; I suppose catapult better as kubeconfigs without expiry aren't production ready.

Thing is, I have used the same GKE kubeconfig for weeks in the past. Are we sure they are set with expiry?
