### ISSUE TITLE
Ensure cluster setup and destroy can happen on different machines

### ISSUE THREAD

**Issue by prabalsharma** [SUSE/catapult#177]
~from https://github.com/SUSE/cap-terraform/tree/master/eks#instructions~

~Once you're done, destroy your infrastructure with terraform destroy. Note that sometimes, the internet gateway does not get detached and deleted even after 15 minutes and times out. If that happens, you'd have to manually delete the VPC and its dependent resources.~

~This is a blocker for catapult's use in CI.~

 ~eks clean script will either have to use aws cli to clean things or it can use https://github.com/colstrom/cloudstrap/blob/develop/bin/cloudstrap-teardown for easy teardown respecting dependencies.~

The original issue does not exist anymore so `terraform destroy` should be good enough for cleanup. However, there is the issue of the plan, apply and destroy potentially needing to work on different machines so there will need to be some work to make sure that can happen without problems as described in the comment below.

https://github.com/SUSE/catapult/issues/177#issuecomment-616230098

**Comment by prabalsharma** [comment]
eksctl is a good way to delete stuff as AWS tests it to match their documentation. We won't have to maintain our own scripts to delete things

**Comment by andreas-kupries** [comment]
@prabalsharma My questions so far below. I seem to have found answers for several as part of the research while writing them them up. Please still have a look and see if it needs any corrections. And if the questions ring bells about trouble spots to avoid, then knowing these would be nice too ;)

# Questions

With the cluster created by terraform, we will have some collection of
AWS resources.

  - How is that collection of resources mapped to something `eksctl` would understand ?

    I mean, if the cluster is created by `eksctl` it will

      1. know what resources are in the cluster, and will have
      2. stored relevant information in whtever config files it uses.

    With terraform, are your resources matching what `eksctl` does ?
  
    And how to translate/generate a suitable config `eksctl` can then
    use to tear that down ?

    __Answer__ I seem to have managed to answer my own question
    ... Clusters are referenced by name. So if I know the name of the
    cluster created by terraform I may have a chance of destroying
    it. At least what eksctl believes is part of it, vs what our
    terraform setup may create beyond that.

  - Currently looking at the "official" documentation at
    https://eksctl.io/ I am unable to find the cli reference, i.e. the
    full set of commands and their options.

    Ok. It seems you really have to download and install the cli
    locally so that you can use `eksctl help ...` for the commands and
    their options.

    Using that it seems a cluster is referenced by name.

  - Where in `catapult` is the EKS support ?

    __Answer__: `backend/eks/`

  - Looking at the `deploy.sh` script I do not see where we can get the cluster name from ?!

    The `cap-terraform/eks/outputs.tf` seems to only contain code for the kubeconfig.

    I suspect that this is something I have to ask @satadruroy  about.

    Looking a bit more the name might be in the kubeconfig we have. It
    depends on the relationship between `generated-cluster-name` and
    `module.eks.eks-cluster-name`.

I recommend to create a spike looking into using `eksctl` for cluster creation as well.

**Comment by prabalsharma** [comment]
@andreas-kupries can't you grep cluster name from kubeconfig? that can be made available as an input to https://github.com/SUSE/catapult/blob/master/backend/eks/clean.sh
Then all is need is few ekctl command to delete eks cluster and may be some extra commands to delete any left over.

**Comment by satadruroy** [comment]
@andreas-kupries with regards to the cluster name it is possible to extract it from the generated kubeconfig but it's quite a bit brittle compared to having a terraform output for the name itself. So, for example in the kubeconfig for an EKS cluster I setup with TF here is what I see:

```
<snipped>
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "cap-mdgdlrhh"
```

**Comment by satadruroy** [comment]
As for setting up an EKS cluster with `eksctl` here is what I did (though the IAM permissions needed are a bit of a mess so I had to get Chris O to sort me out on that) :

```eksctl create cluster --name kubecf --version 1.14 --nodegroup-name standard-workers --node-type t2.large --nodes 3 --nodes-min 1 --nodes-max 3 --node-volume-size 80 -r us-east-2  --managed --ssh-access --ssh-public-key sr-eks-keys```

And destroy: 

```eksctl delete cluster --name kubecf -r us-east-2```

**Comment by andreas-kupries** [comment]
Yes, I saw the cluster name in the kubeconfig ... Was unsure if it was truly the propr name, hence the question to @satadruroy .

For the initial work, i.e. to test that using `eksctl delete cluster` is a feasible way of deleting the terraformed cluster I am ok with grepping it out of the config. (Or using yaml/json).

For the final PR I agree that having it as output from tf is the proper way to go.

Note: Setting up the cluster with eksctl is out of scope here. Hence my recommendation for a new ticket setting up a spike. That is where we can then collect the current knowledge like from the previous comment.

**Comment by andreas-kupries** [comment]
Draft PR = https://github.com/SUSE/catapult/pull/182

**Comment by prabalsharma** [comment]
The idea is to handle deletion using just kubeconfig, because right now we are not transferring any tf related info between job in concourse, just kubeconfig.

**Comment by andreas-kupries** [comment]
Test instructions:
- Use a local catapult
- Configure for
  ```export BACKEND=eks
  export ENABLE_EIRINI=false
  export SCF_OPERATOR=true
  ```
- Provide a clustre name, or not.
- Run the targets `k8s`, `scf`, and `clean`.
  IOW deploy kube cluster, deploy kubecf on top, then remove everything again.

**Comment by satadruroy** [comment]
Based on what @andreas-kupries has found so far it doesn't seem cleaning up a terraform provisioned cluster with `eksctl delete` is going to work as `eksctl` looks for a corresponding cloudformation stack that doesn't exist. Seems like there are two options for Catapult to provision and destroy and EKS cluster in a consistent way:

1. Catapult uses `eksctl` to provision as well as destroy an EKS cluster. The actual mechanics of setting up an EKS cluster should be an implementation detail within Catapult and should not impact the pipelines as the interface between the CI pipeline and Catapult should not change (the same info set needed for setting up a cluster regardless of _how_ it is done).

2. Use Terraform to do both provisioning and cleanup. So `terraform destroy` would also happen from within Catapult but this would require the following steps:

a.  Use a 'remote backend' to store the terraform state information, i.e an S3 bucket and Catapult does a `terraform init` with backend configuration before it does a plan and apply.

(https://www.terraform.io/docs/backends/types/s3.html)



b. After plan completes, Catapult archives the entire working directory, including the .terraform subdirectory created during init, and saves it somewhere where it will be available to the apply/destroy step. A common choice is as a "build artifact" within the chosen orchestration tool. 

(see the section on "Plan and Apply on different machines" at https://learn.hashicorp.com/terraform/development/running-terraform-in-automation)

c. Before running destroy, Catapult obtains the archive created in the previous step and extracts it at the same absolute path and finally runs `terraform destroy`

Step a., strictly speaking, is not necessary as we can use the local backend too but the `terraform.tfstate` may contain sensitive information such as access credentials so using a remote backend with better access control and encryption capabilities is preferred. Regardless, copying the terraform assets (step b) above and making it available before step c. runs is unavoidable.   

I've tested the approach above with Terraform and it works (basically running the init/plan/apply and init/destroy from two different directories) but 1. does seem like a simpler option.

(Note that the original reported issue does not exist any more, i.e. `terraform destroy` consistently cleans up the cluster without leaving anything behind).

**Comment by viccuad** [comment]
Many thanks Satadru for the swift summary.

I side with option 2: creationg and deletion with terraform, saving `.terraform` securely to be consumed on deletion. As said, `terraform destroy` doesn't leave anything behind.

This approach has the benefit that it's the same for all cloud backends, we keep consuming and testing SUSE/cap-terraform for customers, facilitates hybrid clouds, and imho it's more extendable.

For this option 2 approach we need a solid pool system.

**Comment by andreas-kupries** [comment]
Notes from me ... The existing code is all terraform, for both create and destroy.

The reason for trying out `eksctl` on the destroy side was issues with terraform not fully cleaning up.
And these issues seem to be gone.

The new issue left is to support create/destroy happening on different machines, i.e. different containers/tasks of the pipeline. And the code for handling that (save/restore terraform state to s3 etc.) I believe is better placed in the scripts of the pipeline itself instead of catapult. Putting such into catapult would tie it very much to the SUSE infrastructure (s3 buckets) and CI pipeline, which I consider as a bad idea.

While we are keeping the ticket here the actual work will be in the https://github.com/SUSE/cap/ repository

The draft PR #182 will be closed, it is now irrelevant.

**Comment by andreas-kupries** [comment]
Results so far ...

Sequences:
# k8s scf clean - Leaves behind kubecf volumes. Stops on VPC deletion.
# k8s scf scf-clean clean - All volumes properly gone. Stops on VPC deletion.
# k8s clean - Stops on VPC deletion. Albeit it seems to take longer before TF gives up.

So, the fact that catapult `clean` does not invoke `scf-clean` when kubecf was deployed is the reason why volumes are left behind. Teardown has to manually `scf-clean` to prevent that.

The issue with VPC deletion ...  I have no idea yet. Is VPC an explicit resource under TF control ? If yes, does it have a TF flag to force recursive deletion ? If yes, we should set it.

The VPC error is
```
Error: Error deleting VPC: DependencyViolation: The vpc 'vpc-0ac40b647fc6d850b' has dependencies and cannot be deleted.
	status code: 400, request id: f62d8a07-d216-444f-9348-41bb37ebe1dd
```

This error happens __after__ the cluster (EKS) is destroyed, and most other things too.

Trying to `make clean` again causes the re-invoked terraform to return
```
________________________________ clean
make -s -C backend/eks clean
/work/SUSE/dev/catapult/buildcleaner /work/SUSE/dev/catapult/backend/eks
ℹ  🚀  eks ☸ cleaner  🎂  ./clean.sh ➤  Loading
/work/SUSE/dev/catapult/buildcleaner/cap-terraform/eks /work/SUSE/dev/catapult/buildcleaner /work/SUSE/dev/catapult/backend/eks
module.network.random_string.cluster_name: Refreshing state... [id=dobrpwvy]
data.aws_region.current: Refreshing state...
module.network.data.aws_availability_zones.available: Refreshing state...
module.network.aws_vpc.main: Refreshing state... [id=vpc-0ac40b647fc6d850b]
data.aws_availability_zones.available: Refreshing state...
module.eks.data.aws_iam_policy_document.worker-role-policy: Refreshing state...
module.eks.data.aws_iam_policy_document.cluster-role-policy: Refreshing state...
module.eks.data.aws_ami.eks-worker: Refreshing state...
module.services.data.aws_eks_cluster_auth.eks-auth: Refreshing state...
module.services.data.aws_eks_cluster.eks: Refreshing state...

Error: error reading EKS Cluster (cap-dobrpwvy): ResourceNotFoundException: No cluster found for name: cap-dobrpwvy.
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "3bd0f3fb-04f5-4494-8c4d-32c42933b98a"
  },
  Message_: "No cluster found for name: cap-dobrpwvy."
}

  on modules/services/k8s.tf line 1, in data "aws_eks_cluster" "eks":
   1: data "aws_eks_cluster" "eks" {
```

So, terraform is left in a state where it cannot clear things further.

A manual cleanup of the VPC from the AWS console works, after confirming that I want to delete it __and dependent__ resources.

From the responses seen the dependent resources may have been security groups.

After deleting the VPC it is necessary manually delete the __build....__ directory, as catapult cannot (see above failure for EKS cluster).

**Comment by andreas-kupries** [comment]
Results so far ...

Sequences:
# k8s scf clean - Leaves behind kubecf volumes. Stops on VPC deletion.
# k8s scf scf-clean clean - All volumes properly gone. Stops on VPC deletion.
# k8s clean - Stops on VPC deletion. Albeit it seems to take longer before TF gives up.

So, the fact that catapult `clean` does not invoke `scf-clean` when kubecf was deployed is the reason why volumes are left behind. Teardown has to manually `scf-clean` to prevent that.

The issue with VPC deletion ...  I have no idea yet. Is VPC an explicit resource under TF control ? If yes, does it have a TF flag to force recursive deletion ? If yes, we should set it.

The VPC error is
```
Error: Error deleting VPC: DependencyViolation: The vpc 'vpc-0ac40b647fc6d850b' has dependencies and cannot be deleted.
	status code: 400, request id: f62d8a07-d216-444f-9348-41bb37ebe1dd
```

This error happens __after__ the cluster (EKS) is destroyed, and most other things too.

Trying to `make clean` again causes the re-invoked terraform to return
```
________________________________ clean
make -s -C backend/eks clean
/work/SUSE/dev/catapult/buildcleaner /work/SUSE/dev/catapult/backend/eks
ℹ  🚀  eks ☸ cleaner  🎂  ./clean.sh ➤  Loading
/work/SUSE/dev/catapult/buildcleaner/cap-terraform/eks /work/SUSE/dev/catapult/buildcleaner /work/SUSE/dev/catapult/backend/eks
module.network.random_string.cluster_name: Refreshing state... [id=dobrpwvy]
data.aws_region.current: Refreshing state...
module.network.data.aws_availability_zones.available: Refreshing state...
module.network.aws_vpc.main: Refreshing state... [id=vpc-0ac40b647fc6d850b]
data.aws_availability_zones.available: Refreshing state...
module.eks.data.aws_iam_policy_document.worker-role-policy: Refreshing state...
module.eks.data.aws_iam_policy_document.cluster-role-policy: Refreshing state...
module.eks.data.aws_ami.eks-worker: Refreshing state...
module.services.data.aws_eks_cluster_auth.eks-auth: Refreshing state...
module.services.data.aws_eks_cluster.eks: Refreshing state...

Error: error reading EKS Cluster (cap-dobrpwvy): ResourceNotFoundException: No cluster found for name: cap-dobrpwvy.
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "3bd0f3fb-04f5-4494-8c4d-32c42933b98a"
  },
  Message_: "No cluster found for name: cap-dobrpwvy."
}

  on modules/services/k8s.tf line 1, in data "aws_eks_cluster" "eks":
   1: data "aws_eks_cluster" "eks" {
```

So, terraform is left in a state where it cannot clear things further.

A manual cleanup of the VPC from the AWS console works, after confirming that I want to delete it __and dependent__ resources.

From the responses seen the dependent resources may have been security groups.

After deleting the VPC it is necessary manually delete the __build....__ directory, as catapult cannot (see above failure for EKS cluster).

**Comment by viccuad** [comment]
> So, the fact that catapult clean does not invoke scf-clean when kubecf was deployed is the reason why volumes are left behind. Teardown has to manually scf-clean to prevent that.

With the external-dns GKE + skeleton for the rest, we now call `scf-clean` inside of `clean` too, as it was needed for deleting GKE correctly.
