### ISSUE TITLE
catapult doesn't provide a way to provision NFS on imported CaaSP clusters

### ISSUE THREAD

**Issue by HartS** [SUSE/catapult#181]
When catapult provisions CaaSP on ECP via terraform, an NFS VM is created to serve as the backend for the nfs-provisioner storageclass installed via helm

When a user provides a CaaSP cluster (for example, one running on their own infrastructure) without a storageclass, catapult needs a way to install a storageclass which can be used to install kubecf, or at least appropriate documentation and appropriate error messages on what the user needs to provide

**Comment by viccuad** [comment]
I don't think provisioning a storage + storageclass is feasible when `BACKEND=imported`, or when `BACKEND=caasp4os make kubeconfig` against unkown CaaSP clusters. We cannot know if the storage to add is a KVM VM, an Openstack one, etc. And discriminately adding hostpath-based storage doesn't sound nice either.

We could add a `BACKEND=caasp4os make caasp4os-prepare` that idempotently adds missing bits (storageclass, clusterroles, etc). The same for future `BACKEND=caasp4kvm`, `BACKEND=caasp4aws`, etc. But TBH I find this moot. If you are operating against that type of cluster, chances are that it has been deployed with catapult and cap-terraform, so why the need to re-prepare it again.

We can indeed fail early and inform the user that the imported cluster is not correctly configured.
Right now we run scf's [`kube-ready-state-check.sh || true`](https://github.com/SUSE/catapult/blob/master/backend/check.sh#L12), so you should see its output.

With https://github.com/cloudfoundry-incubator/kubecf/pull/697 already merged, https://github.com/SUSE/catapult/pull/178 will solve this.
