### ISSUE TITLE
Catapult needs to set DNS via cloud DNS service for hosted kubernetes providers

### ISSUE THREAD

**Issue by HartS** [SUSE/catapult#185]
When LoadBalanced type services are used on hosted kubernetes environments (confirmed with AKS, and expected with GKE and EKS as well), the kubecf, stratos, and metrics deployments need to confirm that public DNS records have been set appropriately before considering a deployment successful.

Previously with cf-ci we scripted a wait 

and used `az network dns` [to wait for loadbalancer services to become ready and then set dns records set records](https://github.com/SUSE/cf-ci/blob/develop/qa-pipelines/tasks/cf-deploy.sh#L57-L58) (regardless of the actual kube provider)

However, we would probably benefit from using something like [external-dns](https://github.com/kubernetes-sigs/external-dns) which would unify the steps for the kubernetes providers we support/test while using their associated dns services

**Comment by viccuad** [comment]
Closing this, since #192 achieved it.
