### ISSUE TITLE
Sleep in code makes deployment logs stall

### ISSUE THREAD

**Issue by pgonin** [SUSE/catapult#197]
I am using catapult on CaaSP4 / AWS with fast storage class
That 'sleep' makes the deployment quite slow...
https://github.com/SUSE/catapult/blob/d2d00bd5afbddde2fd31e5c4ebce51d8ddc525db/modules/scf/install.sh#L104

**Comment by viccuad** [comment]
I couldn't find a rationale by git blaming and going back. Removing it on a kind deployment makes `wait_ns scf` erroneusly continue as the namespace to wait has no pods to wait for upon creation.

I suppose either we just reduce it or fix wait_{ns,pod} etc so they wait for present pods, and then completed ones.

**Comment by mudler** [comment]
The problem is that the cf-operator doesn't create the pods immediately, and the ig pod can take time to pop up.

I'd suggest to use something around the lines of https://github.com/cloudfoundry-incubator/kubecf/pull/346/files#diff-10918aceeac8461bbf38a36e8f06cea2R29
