### ISSUE TITLE
Support for Json configuration files

### ISSUE THREAD

**Issue by mudler** [SUSE/catapult#30]
It would be much easier to use a JSON or YAML structure than using environment variables as it's today. 

This shouldn't replace the env usage, but should instead add the feature to support both ways of running catapult targets.

**Comment by fargozhu** [comment]
It would be much easier to use a JSON or YAML structure than using environment variables as it's today.

**Comment by viccuad** [comment]
As an intermediate step, we could at least read env vars from a default config/path apart from passing them inline. Instead of:

    $> [...] DOCKER_PASSWORD="xxxx" \
             DOCKER_USERNAME="xxxx" \
             DOCKER_ORG="my-org" \
             DOCKER_REGISTRY="my.private.registry" \
             make all

It could all be contained in a `buildir/env.sh` or so, relative to each deployment.

**Comment by mudler** [comment]
> As an intermediate step, we could at least read env vars from a default config/path apart from passing them inline. Instead of:
> 
> ```
> $> [...] DOCKER_PASSWORD="xxxx" \
>          DOCKER_USERNAME="xxxx" \
>          DOCKER_ORG="my-org" \
>          DOCKER_REGISTRY="my.private.registry" \
>          make all
> ```
> 
> It could all be contained in a `buildir/env.sh` or so, relative to each deployment.

I would avoid to do that to leak accidentally sensitive data

**Comment by viccuad** [comment]
woops, badly chosen example, I was thinking on all the rest of config vars that aren't for credentials.
