### ISSUE TITLE
More transparent and clear the make tagets scopes

### ISSUE THREAD

**Issue by mudler** [SUSE/catapult#33]
**Problem:** There is no real differentiation between private and public targets, and backend-private targets are currently used for end-user usage.

We should split make targets between `internal` and `public` so to provide a stable and solid API outside the internal usage. 

This also means that we should document the public one, providing also a description of the arguments that can tweak the targets scopes.

E.g:

Internal:

- `make minikube`
- `make kind`
- `make kind-clean`
- `make minikube-clean`

Public:

- `make cluster` / `make kubernetes`
- `make scf`
- `make clean`
- `make scf-login`
- `make all`

Public (Extra-core functions, Plugins):

- `make ingress` and `make ingress-forward`
- `make terminal`
...

In such way we can define a configuration aka "Context" which our make targets run against. A Context can be a JSON/YAML (https://github.com/SUSE/catapult/issues/30) or a ENV configuration (e.g. `CLUSTER_NAME=gke-test1`, `BACKEND=gke` )

Relates to: https://github.com/SUSE/catapult/issues/40 and https://github.com/SUSE/catapult/issues/34

**Comment by fargozhu** [comment]
@mudler can u describe a little bit more what you want to achieve?

**Comment by viccuad** [comment]
Closing this as everything was already implemented :tada:
