### ISSUE TITLE
Simplify layout of scripts/*

### ISSUE THREAD

**Issue by viccuad** [SUSE/catapult#35]
Currently, the implementation consists of everything flat on `scripts/*`. Add folders per k8s backend, state, etc (`kind/*` ,`caasp4os/*` , `gke/*` , `scf/*` , `tests/*`). It would be nice to document idiosyncrasies or what each state consists of, in wiki, readme files in the folder, etc.

**Comment by viccuad** [comment]
Ongoing work of a possible reimplementation  at `v2-layout` branch, comments welcome

**Comment by mudler** [comment]
> Ongoing work of a possible reimplementation at `v2-layout` branch, comments welcome

Had a quick look. I would invest a bit into porting to functions some of the recurring patterns, e.g. extracting information from configmap (our `cap-values`), wait for namespace, etc.. they should be treated as helpers

**Comment by viccuad** [comment]
I will add topical folders and change the makefile, and open a PR to merge against a `v2` branch. I'm scared of trying to change everything at once and be a bottleneck for the refactoring efforts

**Comment by mudler** [comment]
Closing, fixed in https://github.com/SUSE/catapult/pull/48
