### ISSUE TITLE
Add AKS backend by consuming github.com/SUSE/cap-terraform

### ISSUE THREAD

**Issue by fargozhu** [SUSE/catapult#36]
The setup of a k8s cluster and the deployment of SCF on the three main public cloud providers should be through the existent [cap-terraform](https://github.com/SUSE/cap-terraform) scripts, so we can reuse and contribute to one project only.

**Comment by viccuad** [comment]
Status as of writing this message:
- gke: implemented in `make gke`, leverages cap-terraform.
- eks: effort in add-eks branch. It targets cap-terraform's branch feature/eks-terrform-12. Waiting for https://github.com/SUSE/cap-terraform/pull/12.
- aks: TODO

**Comment by viccuad** [comment]
Deploying on AKS may need some specific options on values.yaml:
from https://cloudfoundry.slack.com/archives/CQ2U3L6DC/p1586124264123900?thread_ts=1586106664.123400&cid=CQ2U3L6DC , 
https://qiita.com/a09-capf/items/b7e70e433d3763e61dad

**Comment by viccuad** [comment]
https://github.com/SUSE/catapult/pull/196 adds the skeleton.

Missing: consuming new terraform variables correctly, and having a full deployment.

**Comment by viccuad** [comment]
Closing this, already done!
