### ISSUE TITLE
Add make target for importing existing clusters

### ISSUE THREAD

**Issue by viccuad** [SUSE/catapult#55]
Currently, if one wants to run catapult make targets against a preexisting target, one needs to do
`CLUSTER_NAME=foo make buildir; cp kubeconfig buildir/`, and make sure that the `cap-values` configmap exists. (see https://github.com/SUSE/catapult/wiki/Import-your-k8s-cluster).

We could streamline this by providing a make target. It may be useful to detect on the target if the cluster is prepared for cap by running the kube-check script from github.com/SUSE/scf, or interactively prompting for values to create a cap-values configmap.

**Comment by mudler** [comment]
I would really like that!

**Comment by viccuad** [comment]
This seems to be more difficult than it looks at first view,

- Needs to work when sourcing the script, and when `direnv` "loads" the script (spawns a bash subshell, executes the shell, captures the difference in env vars, exports the env vars outside).
- Should not use readlink, as for eg. macos may not have it installed by default
- We could use $BASH_SOURCE, but that's only present on bash v3+ (again, macos)
- Should work if sourced from zsh or other shells

**Comment by viccuad** [comment]
Implemented in https://github.com/SUSE/catapult/pull/63
