### ISSUE TITLE
Define variables needed by each module

### ISSUE THREAD

**Issue by mudler** [SUSE/catapult#77]
We could come up with a strategy to define in one place the variables needed per-module, which than could be re-used to generate docs automatically. e.g. an `env.sh` for each module which contains the defaults.

Could be done at the same time when considering: https://github.com/SUSE/catapult/issues/72

**Comment by viccuad** [comment]
We could use `set -u` to fail on undefined vars on all scripts, and load the corresponding `env.sh` for the module. That way at least we know that all needed variables are defined. The only way to know if a variable is defined but not used is by shellcheck or the like.
