### ISSUE TITLE
Move kubecf deployments to its own module

### ISSUE THREAD

**Issue by viccuad** [SUSE/catapult#89]
I would like to separate kubecf deployments into a `modules/kubecf` or the like, by copy pasting the current `scf` module. Right now scf seems that it would be able to be frozen, which would actually help in having a QA tool with less regressions there. Also, kubecf is starting to do things differently and accruing changes.

This would mean the necessity to publicize `make kubecf` instead of `make scf`, though.

**Comment by mudler** [comment]
Makes perfectly sense - But there is no need to break `make scf`. 
It could simply be a soft-wrapper that  redirects to the wanted module

**Comment by viccuad** [comment]
Just realized that having a kubecf module allows us to have `kubecf/defaults.sh`, which simplifies implementation.

I would like to have a `make kubecf`. I understand that offering this api instead of `SCF_OPERATOR=true make scf` is painful for everywhere where we call it. But the options passed to the target to build kubecf, no matter if it stays `make scf` or gets a new `make kubecf` one, will diverge from the ones for deploying scf anyways.

**Comment by viccuad** [comment]
Just pushed an annotated tag `cap-1.5.2` to mark up until what commit was used to test cap-1.5.2 release with scf. It contains info on what was known to work and what was used for `cap-1.5.2` testing.

I vote for removing all scf logic from then onwards.

**Comment by viccuad** [comment]
Doone with https://github.com/SUSE/catapult/pull/211
